### ISSUE TITLE
Add FCEB & Enrollment Column to stakeholders.csv

### ISSUE THREAD

**Issue by KeithBonesJr** [cisagov/cyhy-reports#110]
# 💡 Summary #

Please add a FCEB and Enrolled column to the stakeholders.csv after the cyhy-stakeholder alias is called.

## Motivation and context ##

Internal stakeholders would like to know agencies identified as FCEB and when agencies were enrolled for the service. 

## Implementation notes ##

Please provide details for implementation, such as:

- Add a column to the stakeholders.csv denoting FCEB status.
- Add a column to the stakeholders.csv with the enrolled status

Specific stakeholders.py code found here:  https://github.com/cisagov/cyhy-reports/blob/dc75e103292137bcfef1ef3bd6464b4e9817e418/cyhy_report/stakeholders/stakeholders.py

## Acceptance criteria ##

- [x] New Column named FCEB with Yes/No for FCEB status
- [x] New Column named Enrolled with date of enrollment

**Comment by KeithBonesJr** [comment]
@dav3r  can this issue be assigned to me?

**Comment by dav3r** [comment]
@KeithBonesJr I assigned it to you.  This issue should be improved by specifying which `stakeholders.csv` you are referring to, i.e. which piece of code creates it.
