### ISSUE TITLE
Migrate Mustache rendering from Pystache to Chevron

### ISSUE THREAD

**Issue by mcdonnnj** [cisagov/cyhy-reports#51]
# 🚀 Feature Proposal

Transition from the [Pystache](https://github.com/defunkt/pystache) package to the [Chevron](https://github.com/noahmorrison/chevron) package for rendering [Mustache](https://github.com/mustache/spec) templates in this codebase.

## Motivation

We currently use the [Pystache](https://github.com/defunkt/pystache) package to render [Mustache](https://github.com/mustache/spec) templates for report generation. It has not seen a release in over six years. I think that until we migrate away from using this method for report generation that we should migrate to a maintained package. After looking into this I think that our best bet is the [Chevron](https://github.com/noahmorrison/chevron) package.

## Pitch

Although it has been over a year since its last release, it has seen more recent developer activity, tries to maintain 100% spec compliance, and claims significantly better performance than what is offered by [Pystache](https://github.com/defunkt/pystache). This switch would have us using a newer, and more spec-compliant package. Since we continue to gain new CyHy customers, the speed increase offered might also help report generation under an increasing workload.

A migration appears to be straightforward as the two packages are used in a similar manner. If it is as straightforward as it appears, it would make for a simple transition with testing to verify functionality.

Lastly, as we move forward with a Python 2 to Python 3 transition, it is important to note that the latest version officially supported by [Pystache](https://github.com/defunkt/pystache) is Python 3.3, In comparison, [Chevron](https://github.com/noahmorrison/chevron) offers support through to Python 3.6 (while maintaining support for 2.7 for use pre-transition).

**Comment by dav3r** [comment]
This work was completed in https://github.com/cisagov/cyhy-reports/pull/74.
