### ISSUE TITLE
Implement parallelization  for send notifications

### ISSUE THREAD

**Issue by jasonodoom** [cisagov/cyhy-reports#83]
# 💡 Summary #

The number of stakeholders have grown in cyhy-reports and as such we want to optimize the notification process. 

## Motivation and context ##

 Currently, notifications take longer than expected so the task is to implement parallelization for `create_send_notifications`
 This will speedup the notification process significantly. 

## Implementation notes ##

The implementation will look similar to `create_snapshots_reports_scorecard` But #62 may also be considered. 

## Acceptance criteria ##

This will be tested in a Dev environment. The expectation is notifications should be generated significantly faster than previous runs when compared to the amount of time it has taken for processing to complete.

**Comment by dav3r** [comment]
This has been taken care of with #96.  Note that parallelization was not necessary, due to the relatively small number of notifications that need to be generated each day.  However, the notification generation process was significantly optimized via other means.  See #96 for more details.
