### ISSUE TITLE
Improve report generation logic

### ISSUE THREAD

**Issue by jasonodoom** [cisagov/cyhy-reports#94]
# 💡 Summary #

The number of stakeholders have grown in cyhy-reports and as such we want to optimize the notification process. As discussed recently with @dav3r , #83 is nice but not necessary as this can be solved more simply instead of parallel processing which would be "overkill". 

## Motivation and context ##

Currently, the daily notification process takes much longer than necessary.  The current process is that we iterate over the list of "CyHy report receiving" organizations (and their descendants) and the [notification generator](https://github.com/cisagov/cyhy-reports/blob/develop/cyhy_report/cyhy_notification/generate_notification.py) is blindly called for each organization, regardless of whether or not a notification will be generated for that organization.

To speed up the notification process significantly, [`create_send_notifications.py`](https://github.com/cisagov/cyhy-reports/blob/develop/extras/create_send_notifications.py) should be modified to only call the [notification generator](https://github.com/cisagov/cyhy-reports/blob/develop/cyhy_report/cyhy_notification/generate_notification.py) if we already know it's going to generate a notification.  

## Implementation notes ##

The implementation should use mongo queries to build the correct list of organization IDs that require notifications.  The rewrite for this process should replace the logic in [`build_cyhy_org_list`](https://github.com/cisagov/cyhy-reports/blob/888867b3e13b2868a1ec1657e7612416a2fb9fea/extras/create_send_notifications.py#L46-L61) as that includes the current implementation for the mongo query.

## Acceptance criteria ##

This will be tested in a Dev environment. The expectation is notifications should be generated significantly faster than previous runs when compared to the amount of time it has taken for processing to complete. The reason being that instead of querying our list of agencies we will focus only those in which notifications have been generated. Thus, decreasing processing time and sending notifications quickly.

This should also be tested against Production data by verifying that the correct list of organization IDs can be generated, though this testing MUST NOT write any data to the Production database.

**Comment by dav3r** [comment]
This issue can be closed, courtesy of https://github.com/cisagov/cyhy-reports/pull/96.
